# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(403, 281)
        Dialog.setTabletTracking(False)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color:#2d3033")
        self.time_now = QtWidgets.QLCDNumber(Dialog)
        self.time_now.setGeometry(QtCore.QRect(190, 20, 191, 41))
        self.time_now.setObjectName("time_now")
        self.finish_class = QtWidgets.QPushButton(Dialog)
        self.finish_class.setGeometry(QtCore.QRect(140, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 明體 Std L")
        font.setPointSize(14)
        self.finish_class.setFont(font)
        self.finish_class.setObjectName("finish_class")
        self.finish_class.setStyleSheet("color:#FFFFFF")
        self.now_subject = QtWidgets.QLabel(Dialog)
        self.now_subject.setGeometry(QtCore.QRect(320, 250, 31, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.now_subject.setFont(font)
        self.now_subject.setObjectName("now_subject")
        self.now_subject.setStyleSheet("color:#FFFFFF")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setStyleSheet("color:#FFFFFF")
        self.rest_time = QtWidgets.QLCDNumber(Dialog)
        self.rest_time.setGeometry(QtCore.QRect(190, 140, 191, 41))
        self.rest_time.setMode(QtWidgets.QLCDNumber.Dec)
        self.rest_time.setObjectName("rest_time")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 151, 41))
        self.label_3.setStyleSheet("color:#00FF00")
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 210, 81, 41))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_5.setStyleSheet("color:#FFFFFF")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 151, 41))
        self.label_2.setStyleSheet("color:#FFFFFF")
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.over_time = QtWidgets.QLCDNumber(Dialog)
        self.over_time.setGeometry(QtCore.QRect(190, 80, 191, 41))
        self.over_time.setMode(QtWidgets.QLCDNumber.Dec)
        self.over_time.setObjectName("over_time")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 230, 221, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("color:#FFFFFF")
        # self.rest_time.setStyleSheet("background-color:#4c5054")
        # self.over_time.setStyleSheet("background-color:#4c5054")
        # self.time_now.setStyleSheet("background-color:#4c5054")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.finish_class.setText(_translate("Dialog", "准时下课"))
        self.now_subject.setText(_translate("Dialog", "数学"))
        self.label.setText(_translate("Dialog", "当前时间"))
        self.label_3.setText(_translate("Dialog", "剩余时间"))
        self.label_5.setText(_translate("Dialog", "当前科目"))
        self.label_2.setText(_translate("Dialog", "下课时间"))
        self.label_4.setText(_translate("Dialog", "不拖堂的您最美"))


